# Generated by Django 5.2.1 on 2026-01-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('details', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=0)),
                ('SKU', models.IntegerField(blank=True, max_length=4, unique=True)),
            ],
        ),
    ]
