# Generated by Django 5.2.1 on 2026-01-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='SKU',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
    ]
