# Generated by Django 6.0 on 2026-01-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='SKU',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
