# Generated by Django 6.0 on 2026-01-05 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_item_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('batch_no', models.CharField(max_length=8, unique=True)),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('details', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='storage.item')),
            ],
        ),
    ]
