# Generated by Django 6.0 on 2026-01-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('unit', models.CharField(max_length=100)),
                ('cost', models.IntegerField(max_length=50)),
                ('details', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
