# Generated by Django 6.0 on 2026-01-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
