# Generated by Django 6.0 on 2026-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_raw_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
