# Generated by Django 6.0 on 2026-01-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_raw_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw',
            name='cost',
            field=models.FloatField(max_length=50),
        ),
    ]
