# Generated by Django 6.0 on 2026-01-11 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_raw_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.item')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.raw')),
            ],
        ),
    ]
