# Generated by Django 6.0 on 2026-01-12 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='formula',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.raw'),
        ),
    ]
