# Generated by Django 6.0 on 2026-01-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_item_price_alter_formula_raw_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='storage.item'),
        ),
    ]
