# Generated by Django 6.0 on 2026-01-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_historicalbatch_historicalformula_historicalitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbatch',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'z_Batch History', 'verbose_name_plural': 'historical batchs'},
        ),
    ]
