# Generated by Django 6.0 on 2026-01-15 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_alter_historicalbatch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.item'),
        ),
    ]
