# Generated by Django 6.0 on 2026-01-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_alter_formula_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='cost',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbatch',
            name='cost',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
