# Generated by Django 6.0 on 2026-01-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_batch_cost_historicalbatch_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='price',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
