# Generated by Django 6.0 on 2026-01-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_location_alter_financialentry_location_and_more'),
        ('storage', '0017_alter_historicalitem_price_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField(default=0, help_text='الكمية الكلية اللي استلمها')),
                ('sold_quantity', models.PositiveIntegerField(default=0, help_text='الكمية اللي باعها وسددها')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='سعر القطعة المتفق عليه', max_digits=12)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('last_settlement_date', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.location')),
            ],
        ),
    ]
