# Generated by Django 6.0 on 2026-01-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialentry',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialentry',
            name='user_role',
        ),
        migrations.AddField(
            model_name='financialentry',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalfinancialentry',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
