# Generated by Django 6.0 on 2026-01-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_financialentry_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='location',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='analytics.location'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialentry',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, max_length=200, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='analytics.location'),
        ),
    ]
